# Generated by Django 6.0.1 on 2026-03-09 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='firebase_uid',
            new_name='supabase_uid',
        ),
    ]
