# Generated by Django 6.0.1 on 2026-02-05 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='trip',
            table='trip_details',
        ),
    ]
