# Generated by Django 6.0.1 on 2026-02-07 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_trip_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_location', models.CharField(max_length=255)),
                ('stops', models.JSONField(default=list)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.trip')),
            ],
            options={
                'db_table': 'route_details',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=20)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_details', to='api.trip')),
            ],
            options={
                'db_table': 'vehicle_details',
            },
        ),
    ]
