# Generated by Django 6.0.1 on 2026-02-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_trip_user_route_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
