# Generated by Django 6.0.3 on 2026-03-13 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_completedtrip'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='trip',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.trip'),
            preserve_default=False,
        ),
    ]
