# Generated by Django 6.0.1 on 2026-02-09 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_route_end_datetime_route_start_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_head', models.IntegerField()),
                ('booking_deadline', models.DateTimeField()),
                ('cancel_deadline', models.DateTimeField()),
                ('payment_method', models.CharField(choices=[('UPI', 'UPI'), ('Bank', 'Bank Transfer')], max_length=10)),
                ('upi_id', models.CharField(blank=True, max_length=100, null=True)),
                ('account_no', models.CharField(blank=True, max_length=50, null=True)),
                ('ifsc', models.CharField(blank=True, max_length=20, null=True)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_info', to='api.trip')),
            ],
            options={
                'db_table': 'payment_details',
            },
        ),
    ]
