# Generated by Django 6.0.1 on 2026-02-14 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_trip_passengers_trip_seats_remaining_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripSeats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_capacity', models.IntegerField()),
                ('people_already', models.IntegerField(default=0)),
                ('people_needed', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seats_info', to='api.trip')),
            ],
            options={
                'db_table': 'trip_seats',
            },
        ),
    ]
